name: uammd
channels:
  - conda-forge
dependencies:
  - cmake >=3.22
  - cuda-version 12.*
  - gxx 11.*
  - cuda-libraries-dev
  - cuda-nvcc 
  - make
  - blas-devel
  - liblapacke
  - libblas
  - pybind11
  - python 3.11.*
  - libopenblas=*=*openmp*